export const data = [
    {
        id: 1,
        category: 'tvs',
        img: './Img/p1.png',
        title: 'Samsung TV QLED Q90T',
        priceBefore: 1500,
        price: 550,
        quatify: 1,
    },
    {
        id: 2,
        category: 'celulares',
        img: './Img/p2.png',
        title: 'Samsung Galaxy Note 20 Ultra',
        priceBefore: 870,
        price: 650,
        quatify: 1,
    },
    {
        id: 3,
        category: 'computadores',
        img: './Img/p3.png',
        title: 'Gaming ASUS ROG Strix G15',
        priceBefore: 2000,
        price: 1800,
        quatify: 1,
    },
    {
        id: 4,
        category: 'laptops',
        img: './Img/p4.png',
        title: 'Laptop LENOVO IdeaPad',
        priceBefore: 1050,
        price: 990,
        quatify: 1,
    },
];